#!/usr/bin/env python3
"""Rebuild brain/inspiration/_INDEX.md from the entry files, or search them.

Usage (from the project root, or pass --brain):
  hold_index.py                          rebuild _INDEX.md
  hold_index.py --check                  exit 1 if _INDEX.md is stale (for /hygiene)
  hold_index.py --find "a, b"            list entries matching any term, best first
  hold_index.py --find "a" --surface podcast   ...only entries the user saw landing there
  hold_index.py --dry-run                print the index that would be written

No dependencies. Frontmatter is the simple key: value form; lists are [a, b].
"""
import argparse, os, re, sys

ENTRY = re.compile(r"^\d{4}-\d{2}-\d{2}-.+\.md$")

def aslist(v):
    if v is None: return []
    if isinstance(v, list): return v
    return [v] if v else []

def parse(path):
    text = open(path, encoding="utf-8").read()
    fm, body = {}, text
    if text.startswith("---"):
        parts = text.split("\n---", 1)
        if len(parts) == 2:
            for line in parts[0].splitlines()[1:]:
                if ":" in line:
                    k, v = line.split(":", 1)
                    v = v.strip()
                    if v.startswith("[") and v.endswith("]"):
                        v = [x.strip().strip('"\'') for x in v[1:-1].split(",") if x.strip()]
                    else:
                        v = v.strip('"\'')
                    fm[k.strip()] = v
            body = parts[1]
    m = re.search(r"^# (.+)$", body, re.M)
    fm["_title"] = m.group(1).strip() if m else os.path.basename(path)
    m = re.search(r"## What I would connect it to\s*\n>\s*(.+)", body)
    fm["_connection"] = m.group(1).strip() if m else ""
    m = re.search(r"## Where I see it landing\s*\n>\s*(.+)", body)
    fm["_landing"] = m.group(1).strip() if m else ""
    fm["_body"] = body
    fm["_file"] = os.path.basename(path)
    return fm

def load(folder):
    out = []
    for name in sorted(os.listdir(folder)):
        if ENTRY.match(name):
            out.append(parse(os.path.join(folder, name)))
    out.sort(key=lambda e: e.get("held", e["_file"][:10]), reverse=True)
    return out

def line(e):
    pillars, surfaces, used = aslist(e.get("pillars")), aslist(e.get("surfaces")), aslist(e.get("used_in"))
    tags = f" · {', '.join(pillars)}" if pillars else ""
    where = f" · for {', '.join(surfaces)}" if surfaces else ""
    tail = f" → used in {', '.join(used)}" if e.get("status") == "used" and used else ""
    return f"- {e.get('held','????-??-??')} · {e.get('kind','?')} · **{e['_title']}**{tags}{where}{tail} · `{e['_file']}`"

def render(entries):
    held = [e for e in entries if e.get("status") != "used"]
    used = [e for e in entries if e.get("status") == "used"]
    out = ["# Inspiration index", "",
           "Generated by `hold_index.py`. Do not edit by hand; edit the entry files and rebuild.",
           "One line per entry, newest first: date, kind, title, pillars, where the user saw it",
           "landing, and where it was used. Open the file for the thing itself and the connection.",
           "", f"## Held ({len(held)})", ""]
    out += [line(e) for e in held] or ["(nothing held yet)"]
    out += ["", f"## Used ({len(used)})", ""]
    out += [line(e) for e in used] or ["(nothing used yet)"]
    return "\n".join(out) + "\n"

def find(entries, terms, surface=None):
    terms = [t.strip().lower() for t in terms.split(",") if t.strip()]
    scored = []
    for e in entries:
        if surface and surface.lower() not in [s.lower() for s in aslist(e.get("surfaces"))]:
            continue
        hay = (e["_title"] + " " + e["_body"] + " " + " ".join(aslist(e.get("pillars")))).lower()
        score = sum(hay.count(t) for t in terms)
        if score:
            scored.append((score, e))
    scored.sort(key=lambda x: (x[1].get("status") == "used", -x[0]))
    for score, e in scored:
        flag = " (USED: " + ", ".join(aslist(e.get("used_in"))) + ")" if e.get("status") == "used" else ""
        where = ", ".join(aslist(e.get("surfaces"))) or "not sure yet"
        print(f"{e['_file']}{flag}\n  {e['_title']} [{e.get('kind','?')}] source: {e.get('source','')}\n  connect: {e['_connection']}\n  landing: {e['_landing'] or where}\n")
    if not scored:
        print("nothing held fits those terms" + (f" for {surface}" if surface else ""))

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--brain", default="brain", help="path to the brain folder (default ./brain)")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--find")
    ap.add_argument("--surface", help="with --find: only entries whose surfaces include this")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    folder = os.path.join(a.brain, "inspiration")
    if not os.path.isdir(folder):
        print(f"no inspiration folder at {folder}", file=sys.stderr)
        sys.exit(2)
    entries = load(folder)
    if a.find:
        return find(entries, a.find, a.surface)
    text = render(entries)
    idx = os.path.join(folder, "_INDEX.md")
    if a.dry_run:
        print(text, end=""); return
    if a.check:
        cur = open(idx, encoding="utf-8").read() if os.path.exists(idx) else ""
        if cur != text:
            print("_INDEX.md is stale; run hold_index.py to rebuild"); sys.exit(1)
        print(f"_INDEX.md is current ({len(entries)} entries)"); return
    open(idx, "w", encoding="utf-8").write(text)
    print(f"wrote {idx}: {len(entries)} entries")

if __name__ == "__main__":
    main()
